on:
  workflow_run:
    workflows: ['Pretty and Lint']
    types:
      - completed
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Add VPS to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts
          cat ~/.ssh/known_hosts

      - name: Install dependencies
        run: npm install

      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no -T ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }} << 'EOF'
            set -x  
            echo "Connected to VPS"
            cd dev/zhero
            echo "Changed directory to dev/zhero"
            git pull
            echo "Git pull completed"
            npm install
            echo "npm install completed"
          EOF

      - name: Start zhero_bot container and zhero_db container
        run: |
          ssh ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }} << 'EOSSH'
            cd dev/zhero
            sudo docker compose up -d --build
          EOSSH
