name: Pretty and Lint

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run Prettier
        run: npm run prettier --if-present -- --write .

      - name: Run ESLint
        run: npm run lint --if-present -- --fix .
